language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: false
notifications:
  on_success:
    - change
  on_failure:
    - change
cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  apt:
    packages:
      - graphviz
script:
  - cd ./schemacrawler-parent
  - mvn -Dcomplete clean package jacoco:report coveralls:report
before_deploy:
  - cd ..
  - git fetch --tags
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    keep-history: true
    verbose: true
    on:
      repo: sualeh/SchemaCrawler
      branch: master
      tags: true
    local_dir: "./schemacrawler-distrib/target/_website"
    email: "sualeh@hotmail.com"
    name: "Sualeh Fatehi"
